project:
  type: website
  output-dir: _site
  preview:
    port: 4200
execute:
  freeze: auto
website:
  favicon: favicon.ico
  title: "Syldavia Gazette Beta"
  back-to-top-navigation: true
  open-graph: true
  site-url: https://beta.syldavia-gazette.org
  repo-url: https://github.com/front-matter/syldavia-gazette
  repo-actions: [edit, issue]
  navbar:
    background: light
    logo: "/images/favicon.png"
    logo-alt: "Syldavia Gazette Beta"
    left:
      - text: "Blog"
        file: index.qmd
      - text: "Notebooks"
        file: notebooks.qmd
    tools:
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/front-matter/syldavia-gazette
  page-footer:
    left: "Copyright &copy;2023 Syldavia Gazette."
    center:
      - text: "About"
        href: about.qmd
      - text: "Privacy Policy"
        href: privacy-policy.qmd
      - text: "Newsletter"
        href: newsletter.qmd
    right:
      - icon: rss
        href: index.xml
      - icon: envelope
        href: mailto:info@front-matter.io
      - icon: mastodon 
        href: https://rogue-scholar.social/@syldavia_gazette 
      - icon: github
        href: https://github.com/front-matter/syldavia-gazette
format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: darkly
    linkcolor: "#b91c1c"
    css: styles.css
    toc: true
    toc-location: left
    comments:
      giscus: 
        repo: front-matter/syldavia-gazette
author: 
  name: Martin Fenner
  orcid: "0000-0003-1419-2405"
