project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  favicon: favicon.ico
  title: "Syldavia Gazette Beta"
  back-to-top-navigation: true
  open-graph: true
  site-url: https://beta.syldavia-gazette.org
  repo-url: https://github.com/front-matter/syldavia-gazette
  repo-actions: [edit, issue]
  navbar:
    background: light
    tools:
    - icon: github
      href: https://github.com/front-matter/syldavia-gazette
  sidebar:
    style: "docked"
    border: true
    contents:
      - section: "Pages"
        contents:
        - about.qmd
        - newsletter.qmd
        - privacy-policy.qmd
      - section: "Notebooks"
        contents:
          - retraction_watch.ipynb
          - weekly_digest.ipynb
  page-footer:
    left: "Copyright &copy;2023 Syldavia Gazette."
    right:
      - icon: envelope
        href: mailto:info@front-matter.io
      - icon: mastodon 
        href: https://rogue-scholar.social/@syldavia_gazette 
      - icon: github
        href: https://github.com/front-matter/syldavia-gazette
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
